export const COURSES_REQUEST = "COURSES_REQUEST";
export const COURSES_SUCCESS = "COURSES_SUCCESS";
export const COURSES_FAIL = "COURSES_FAIL";

export const COURSE_DETAIL_REQUEST = "COURSE_DETAIL_REQUEST";
export const COURSE_DETAIL_SUCCESS = "COURSE_DETAIL_SUCCESS";
export const COURSE_DETAIL_FAIL = "COURSE_DETAIL_FAIL";

export const CART_ADD_ITEM = "COURSE_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
